/******************************************************************************
Finite State Machine
Project: micromads.dot
Description: micromads

Generated by gv2fsm, see https://github.com/pbosetti/gv2fsm
gv2fsm version 2.0.0
Generation date: 2026-08-11 18:09:14
Generated from: micromads.dot
The finite state machine has:
  8 states
  11 distinct transition functions
  13 transitions with an associated function

******************************************************************************/

#ifndef MICROMADS_H
#define MICROMADS_H
#ifdef __cplusplus
extern "C" {
#endif
#include <stdlib.h>

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
typedef void state_data_t;


// NOTHING SHALL BE CHANGED AFTER THIS LINE!


// List of states
typedef enum {
  STATE_INIT = 0,  
  STATE_DISCONNECTED,  
  STATE_REQ_CONNECTING,  
  STATE_REQ_WAIT_SETTINGS,  
  STATE_REQ_WAIT_TIMECODE,  
  STATE_PUBSUB_CONNECTING,  
  STATE_READY,  
  STATE_ERROR,  
  NUM_STATES,
  NO_CHANGE
} state_t;

// State human-readable names
extern const char *state_names[];

// State function and state transition prototypes
typedef state_t state_func_t(state_data_t *data);
typedef void transition_func_t(state_data_t *data);

// State functions
// Function to be executed in state init
// valid return states: STATE_DISCONNECTED
state_t do_init(state_data_t *data);
// Function to be executed in state disconnected
// valid return states: STATE_REQ_CONNECTING
state_t do_disconnected(state_data_t *data);
// Function to be executed in state req_connecting
// valid return states: STATE_REQ_WAIT_SETTINGS, STATE_ERROR
state_t do_req_connecting(state_data_t *data);
// Function to be executed in state req_wait_settings
// valid return states: STATE_REQ_WAIT_TIMECODE, STATE_ERROR
state_t do_req_wait_settings(state_data_t *data);
// Function to be executed in state req_wait_timecode
// valid return states: STATE_PUBSUB_CONNECTING, STATE_ERROR
state_t do_req_wait_timecode(state_data_t *data);
// Function to be executed in state pubsub_connecting
// valid return states: STATE_READY, STATE_ERROR
state_t do_pubsub_connecting(state_data_t *data);
// Function to be executed in state ready
// valid return states: NO_CHANGE, STATE_READY, STATE_ERROR
state_t do_ready(state_data_t *data);
// Function to be executed in state error
// valid return states: STATE_DISCONNECTED
state_t do_error(state_data_t *data);


// List of state functions
extern state_func_t *const state_table[NUM_STATES];


// Transition functions
void init_to_disconnected(state_data_t *data);
void on_start(state_data_t *data);
void on_tcp_connected(state_data_t *data);
void on_tcp_error(state_data_t *data);
void on_settings_rx(state_data_t *data);
void on_timeout(state_data_t *data);
void on_timecode_rx(state_data_t *data);
void on_pubsub_ready(state_data_t *data);
void stay(state_data_t *data);
void on_connection_lost(state_data_t *data);
void on_reset(state_data_t *data);

// Table of transition functions
extern transition_func_t *const transition_table[NUM_STATES][NUM_STATES];

// state manager
state_t run_state(state_t cur_state, state_data_t *data);

#ifdef __cplusplus
}
#endif
#endif // MICROMADS_H
