/******************************************************************************
Finite State Machine
Project: micromads.dot
Description: micromads

Generated by gv2fsm, see https://github.com/pbosetti/gv2fsm
gv2fsm version 2.0.0
Generation date: 2026-08-11 18:09:14
Generated from: micromads.dot
The finite state machine has:
  8 states
  11 distinct transition functions
  13 transitions with an associated function

******************************************************************************/
#include "micromads.h"
/* USER CODE BEGIN includes */
#include "mm_types.h"
#include "mm_zmtp.h"
#include "mm_parser.h"
#include <string.h>
#include <stdio.h>
/* USER CODE END includes */

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *state_names[] = { "init", "disconnected", "req_connecting", "req_wait_settings", "req_wait_timecode", "pubsub_connecting", "ready", "error" };

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
  do_init, // in state init
  do_disconnected, // in state disconnected
  do_req_connecting, // in state req_connecting
  do_req_wait_settings, // in state req_wait_settings
  do_req_wait_timecode, // in state req_wait_timecode
  do_pubsub_connecting, // in state pubsub_connecting
  do_ready, // in state ready
  do_error, // in state error
};

// Table of transition functions
transition_func_t *const transition_table[NUM_STATES][NUM_STATES] = {
  { NULL, init_to_disconnected, NULL, NULL, NULL, NULL, NULL, NULL }, 
  { NULL, NULL, on_start, NULL, NULL, NULL, NULL, NULL }, 
  { NULL, NULL, NULL, on_tcp_connected, NULL, NULL, NULL, on_tcp_error }, 
  { NULL, NULL, NULL, NULL, on_settings_rx, NULL, NULL, on_timeout }, 
  { NULL, NULL, NULL, NULL, NULL, on_timecode_rx, NULL, on_timeout }, 
  { NULL, NULL, NULL, NULL, NULL, NULL, on_pubsub_ready, on_tcp_error }, 
  { NULL, NULL, NULL, NULL, NULL, NULL, stay, on_connection_lost }, 
  { NULL, on_reset, NULL, NULL, NULL, NULL, NULL, NULL }, 
};

/* USER CODE BEGIN globals */
/* USER CODE END globals */
/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *   __                  _   _
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: STATE_DISCONNECTED
state_t do_init(state_data_t *data) {
  state_t next_state = STATE_DISCONNECTED;
  /* USER CODE BEGIN do_init */
  /* Your Code Here */

  micromads_agent_t *agent = (micromads_agent_t *)data;
  agent -> state_tick = HAL_GetTick();

  /* USER CODE END do_init */
  switch (next_state) {
  case STATE_DISCONNECTED:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state disconnected
// valid return states: STATE_REQ_CONNECTING
state_t do_disconnected(state_data_t *data) {
  state_t next_state = STATE_REQ_CONNECTING;
  /* USER CODE BEGIN do_disconnected */
  /* Your Code Here */

  micromads_agent_t *agent = (micromads_agent_t *)data;
  agent -> rx_index = 0;
  agent -> state_tick = 0;

  /* USER CODE END do_disconnected */
  switch (next_state) {
  case STATE_REQ_CONNECTING:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state req_connecting
// valid return states: STATE_REQ_WAIT_SETTINGS, STATE_ERROR
state_t do_req_connecting(state_data_t *data) {
  state_t next_state = STATE_REQ_WAIT_SETTINGS;
  /* USER CODE BEGIN do_req_connecting */
  /* Your Code Here */

  micromads_agent_t *agent = (micromads_agent_t *)data;

  if (!mm_zmtp_connect_socket(agent, agent->broker_ip, agent->broker_port, MM_ZMQ_SOCKET_REQ, &agent->req_pcb)) {
    next_state = STATE_ERROR;
  }

  /* USER CODE END do_req_connecting */
  switch (next_state) {
  case STATE_REQ_WAIT_SETTINGS:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state req_wait_settings
// valid return states: STATE_REQ_WAIT_TIMECODE, STATE_ERROR
state_t do_req_wait_settings(state_data_t *data) {
  state_t next_state = STATE_REQ_WAIT_TIMECODE;
  /* USER CODE BEGIN do_req_wait_settings */
  /* Your Code Here */

  micromads_agent_t *agent = (micromads_agent_t *)data;
  static bool request_sent = false;

  if (!request_sent) {
    if (mm_zmtp_send_settings_request(agent)) {
      request_sent = true;
      agent -> state_tick = 0;
    } else {
      next_state = STATE_ERROR;
    }
  } else {
    if (agent -> rx_index > 0) {
      
      if (mm_parse_settings((const char *)agent -> rx_buffer, &agent -> config, agent -> broker_ip)) {
        request_sent = false;
        agent -> rx_index = 0; 
        next_state = STATE_REQ_WAIT_TIMECODE;
      } else {
        request_sent = false;
        agent -> rx_index = 0; 
        next_state = STATE_ERROR;
      }
    } else {

      agent -> state_tick++;
      if (agent -> state_tick > 5000) { // simulated timeout
        request_sent = false;
        next_state = STATE_ERROR;
      } else {
        next_state = NO_CHANGE;
      }
    }
  }

  /* USER CODE END do_req_wait_settings */
  switch (next_state) {
  case STATE_REQ_WAIT_TIMECODE:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state req_wait_timecode
// valid return states: STATE_PUBSUB_CONNECTING, STATE_ERROR
state_t do_req_wait_timecode(state_data_t *data) {
  state_t next_state = STATE_PUBSUB_CONNECTING;
  /* USER CODE BEGIN do_req_wait_timecode */
  /* Your Code Here */

  micromads_agent_t *agent = (micromads_agent_t *)data;

  static bool tc_sent = false;

  if (!tc_sent) {
    if (mm_zmtp_send_timecode_request(agent)) {
      tc_sent = true;
      agent -> rx_index = 0; 
    } else {
      next_state = STATE_ERROR;
    }
} else {
    if (agent -> rx_index > 0) {
      
      mm_zmtp_close_pcb(&agent -> req_pcb);

      tc_sent = false;
      agent -> rx_index = 0;
      next_state = STATE_PUBSUB_CONNECTING;
    } else {
      next_state = NO_CHANGE; 
    }
  }
  /* USER CODE END do_req_wait_timecode */
  switch (next_state) {
  case STATE_PUBSUB_CONNECTING:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state pubsub_connecting
// valid return states: STATE_READY, STATE_ERROR
state_t do_pubsub_connecting(state_data_t *data) {
  state_t next_state = STATE_READY;
  /* USER CODE BEGIN do_pubsub_connecting */
  /* Your Code Here */

  micromads_agent_t *agent = (micromads_agent_t *)data;

  // opening pub socket
  if (!mm_zmtp_connect_socket(agent, agent -> config.pub_endpoint_ip, agent -> config.pub_endpoint_port, MM_ZMQ_SOCKET_PUB, &agent -> pub_pcb)) {
      next_state = STATE_ERROR;
  }

  if (!mm_zmtp_connect_socket(agent, agent -> config.sub_endpoint_ip, agent -> config.sub_endpoint_port, MM_ZMQ_SOCKET_SUB, &agent -> sub_pcb)) {
      next_state = STATE_ERROR;
  }

  // send subscription request to topic
  // if (!mm_zmtp_send_subscribe(agent -> sub_pcb, agent -> config.sub_topic)) {
  //     next_state = STATE_ERROR;
  // }

  /* USER CODE END do_pubsub_connecting */
  switch (next_state) {
  case STATE_READY:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state ready
// valid return states: NO_CHANGE, STATE_READY, STATE_ERROR
state_t do_ready(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* USER CODE BEGIN do_ready */
  /* Your Code Here */
  micromads_agent_t *agent = (micromads_agent_t *)data;

  // operation of while(1)

  /* USER CODE END do_ready */
  switch (next_state) {
  case NO_CHANGE:
  case STATE_READY:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state error
// valid return states: STATE_DISCONNECTED
state_t do_error(state_data_t *data) {
  state_t next_state = STATE_DISCONNECTED;
  /* USER CODE BEGIN do_error */
  /* Your Code Here */

  /* USER CODE END do_error */
  switch (next_state) {
  case STATE_DISCONNECTED:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */    
                                          
// This function is called in 1 transition:
// 1. from init to disconnected
void init_to_disconnected(state_data_t *data) {
  /* USER CODE BEGIN init_to_disconnected */
  /* Your Code Here */
  /* USER CODE END init_to_disconnected */
}

// This function is called in 1 transition:
// 1. from disconnected to req_connecting
void on_start(state_data_t *data) {
  /* USER CODE BEGIN on_start */
  /* Your Code Here */
  /* USER CODE END on_start */
}

// This function is called in 1 transition:
// 1. from req_connecting to req_wait_settings
void on_tcp_connected(state_data_t *data) {
  /* USER CODE BEGIN on_tcp_connected */

  /*
    micromads_agent_t *agent = (micromads_agent_t *)data;
  if (agent->req_pcb != NULL) {
    mm_zmtp_send_greeting(agent->req_pcb);
    mm_zmtp_send_ready(agent->req_pcb, MM_ZMQ_SOCKET_REQ);
  }
  
  if (agent->pub_pcb != NULL) {
    mm_zmtp_send_greeting(agent->pub_pcb);
    mm_zmtp_send_ready(agent->pub_pcb, MM_ZMQ_SOCKET_PUB);
  }
  if (agent->sub_pcb != NULL) {
    mm_zmtp_send_greeting(agent->sub_pcb);
    mm_zmtp_send_ready(agent->sub_pcb, MM_ZMQ_SOCKET_SUB);
    mm_zmtp_send_subscribe(agent->sub_pcb, agent->config.sub_topic);
  }

  */
  /* Your Code Here */
  /* USER CODE END on_tcp_connected */
}

// This function is called in 2 transitions:
// 1. from req_connecting to error
// 2. from pubsub_connecting to error
void on_tcp_error(state_data_t *data) {
  /* USER CODE BEGIN on_tcp_error */
  /* Your Code Here */
  /* USER CODE END on_tcp_error */
}

// This function is called in 1 transition:
// 1. from req_wait_settings to req_wait_timecode
void on_settings_rx(state_data_t *data) {
  /* USER CODE BEGIN on_settings_rx */
  /* Your Code Here */
  /* USER CODE END on_settings_rx */
}

// This function is called in 2 transitions:
// 1. from req_wait_settings to error
// 2. from req_wait_timecode to error
void on_timeout(state_data_t *data) {
  /* USER CODE BEGIN on_timeout */
  /* Your Code Here */
  /* USER CODE END on_timeout */
}

// This function is called in 1 transition:
// 1. from req_wait_timecode to pubsub_connecting
void on_timecode_rx(state_data_t *data) {
  /* USER CODE BEGIN on_timecode_rx */
  /* Your Code Here */
  /* USER CODE END on_timecode_rx */
}

// This function is called in 1 transition:
// 1. from pubsub_connecting to ready
void on_pubsub_ready(state_data_t *data) {
  /* USER CODE BEGIN on_pubsub_ready */
  /* Your Code Here */
  /* USER CODE END on_pubsub_ready */
}

// This function is called in 1 transition:
// 1. from ready to ready
void stay(state_data_t *data) {
  /* USER CODE BEGIN stay */
  /* Your Code Here */
  /* USER CODE END stay */
}

// This function is called in 1 transition:
// 1. from ready to error
void on_connection_lost(state_data_t *data) {
  /* USER CODE BEGIN on_connection_lost */
  /* Your Code Here */
  /* USER CODE END on_connection_lost */
}

// This function is called in 1 transition:
// 1. from error to disconnected
void on_reset(state_data_t *data) {
  /* USER CODE BEGIN on_reset */
  /* Your Code Here */
  /* USER CODE END on_reset */
}


/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|
 *                              |___/
 */

state_t run_state(state_t cur_state, state_data_t *data) {
  state_t new_state = state_table[cur_state](data);
  if (new_state == NO_CHANGE) new_state = cur_state;

  transition_func_t *transition = transition_table[cur_state][new_state];
  if (transition)
    transition(data);

  return new_state;
};

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
  state_t cur_state = STATE_INIT;
  do {
    cur_state = run_state(cur_state, NULL);
    sleep(1);
  } while (1);
  return 0;
}

#endif
